services:
  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: chatdb
    ports:
      - '3306:3306'

  # backend:
  #   build: ./backend
  #   ports:
  #     - '3000:3000'
  #   depends_on:
  #     - db
  #   environment:
  #     DATABASE_HOST: db
  #     DATABASE_PORT: 3306
  #     DATABASE_USERNAME: root
  #     DATABASE_PASSWORD: password
  #     DATABASE_NAME: chatdb

  # frontend:
  #   build: ./frontend
  #   ports:
  #     - '5000:5000'
